version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "questionnaire-viewer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ihnnj14v4c23"
s3_prefix = "questionnaire-viewer"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

