AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  questionnaire-viewer

  Sample SAM Template for questionnaire-viewer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  questionnaireViewerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: questionnaire-viewer/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        questionnaireViewer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /viewer
            RequestParameters:
              - method.request.querystring.name
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  questionnaireViewerApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/viewer/{name}"
  questionnaireViewerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt questionnaireViewerFunction.Arn
  questionnaireViewerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt questionnaireViewerFunctionRole.Arn
